### ISSUE TITLE
Hacking guide by q4ik

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation-wiki#108]
I was gonna add this hacking guide to the wiki, any objections? 

![Hacking_Cheatsheet](https://user-images.githubusercontent.com/15893891/162779847-64adf85e-a8c7-469f-bc51-b924f38be8b3.png)

**Comment by PerfectTangent** [comment]
Pull Requests should be used to for this sort of request, not an issue.

That being said, yes it looks very help. A dark mode version would be extra lit.
